# Generated by Django 5.2.16 on 2026-07-10 08:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد تخفیف')),
                ('kind', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع')),
                ('value', models.PositiveBigIntegerField(help_text='درصد یا تومان', verbose_name='مقدار')),
                ('max_discount', models.PositiveBigIntegerField(blank=True, help_text='فقط برای نوع درصدی', null=True, verbose_name='سقف تخفیف (تومان)')),
                ('min_order_amount', models.PositiveBigIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف کل استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده\u200cشده')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='سقف استفاده هر کاربر')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(verbose_name='معتبر تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ تخفیف')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='discounts.coupon', verbose_name='کد تخفیف')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_uses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کد',
                'verbose_name_plural': 'استفاده\u200cها از کد',
            },
        ),
    ]
