# Generated by Django 5.2.16 on 2026-07-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=11, verbose_name='گیرنده')),
                ('message', models.TextField(verbose_name='متن')),
                ('kind', models.CharField(choices=[('settlement_reminder', 'یادآوری تسویه'), ('order', 'سفارش'), ('other', 'سایر')], default='other', max_length=30, verbose_name='نوع')),
                ('provider', models.CharField(blank=True, max_length=30, verbose_name='ارائه\u200cدهنده')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شد')),
                ('provider_ref', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ پیامک\u200cها',
            },
        ),
    ]
