# Generated by Django 5.2.17 on 2026-09-26 20:26

import re

from django.db import migrations, models

# Password-reset texts sent before this migration were logged with the code in
# clear; they are reclassified as verification messages and masked.
RESET_MARKER = "کد بازیابی"
CODE = re.compile(r"\d{4,}")


def mask_existing_codes(apps, schema_editor):
    SmsLog = apps.get_model("notifications", "SmsLog")
    for log in SmsLog.objects.filter(message__contains=RESET_MARKER).iterator():
        log.message = CODE.sub(lambda match: "*" * len(match.group()), log.message)
        log.kind = "verification"
        log.save(update_fields=["message", "kind"])


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smslog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("settlement_reminder", "یادآوری تسویه"),
                    ("order", "سفارش"),
                    ("verification", "کد تایید"),
                    ("other", "سایر"),
                ],
                default="other",
                max_length=30,
                verbose_name="نوع",
            ),
        ),
        migrations.RunPython(mask_existing_codes, migrations.RunPython.noop),
    ]
