# Generated by Django 5.2.16 on 2026-07-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_hits', to='blog.post', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'بازدید مقاله',
                'verbose_name_plural': 'بازدیدهای مقاله',
                'unique_together': {('post', 'ip')},
            },
        ),
    ]
