# Generated by Django 5.2.16 on 2026-07-21 20:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_rarepartrequest'),
        ('orders', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rate', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'درصد پورسانت دسته\u200cبندی',
                'verbose_name_plural': 'درصد پورسانت دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال شود، برای سفارش\u200cهای جدید پورسانتی ثبت نمی\u200cشود.', verbose_name='فعال')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد پیش\u200cفرض')),
                ('rate_for_shopkeeper', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد برای فروشگاه\u200cها')),
                ('rate_for_customer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد برای کاربران عادی')),
                ('min_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='حداقل مجاز')),
                ('max_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='حداکثر مجاز')),
                ('accrue_on_credit_order', models.BooleanField(default=True, help_text='خاموش باشد، پورسانت خرید اعتباری فقط پس از تسویه ثبت می\u200cشود.', verbose_name='ثبت پورسانت خرید اعتباری هنگام ثبت سفارش')),
                ('notify_on_new_commission', models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی پیامکی پورسانت جدید')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_settings', to=settings.AUTH_USER_MODEL, verbose_name='حساب دریافت\u200cکننده پورسانت')),
            ],
            options={
                'verbose_name': 'تنظیمات پورسانت',
                'verbose_name_plural': 'تنظیمات پورسانت',
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_role', models.CharField(db_index=True, max_length=20, verbose_name='نوع خریدار')),
                ('base_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ مبنا')),
                ('effective_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد اعمال\u200cشده')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پورسانت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تسویه سفارش'), ('earned', 'قطعی\u200cشده'), ('paid', 'پرداخت شد'), ('void', 'باطل (سفارش لغو شد)')], db_index=True, default='pending', max_length=12, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_entries', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_commissions', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پورسانت',
                'verbose_name_plural': 'پورسانت\u200cها',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='commissions_status_5700af_idx')],
            },
        ),
    ]
