# Generated by Django 5.2.16 on 2026-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(blank=True, max_length=100, verbose_name='برچسب کوچک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('highlight', models.CharField(blank=True, help_text='این بخش با رنگ نارنجی در خط دوم نمایش داده می\u200cشود.', max_length=200, verbose_name='بخش نارنجی عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='تصویر')),
                ('button_text', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر صفحه اصلی',
                'ordering': ('order', 'id'),
            },
        ),
    ]
