# Generated by Django 5.2.16 on 2026-07-10 08:41

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('ship_to_name', models.CharField(max_length=150, verbose_name='گیرنده')),
                ('ship_to_phone', models.CharField(max_length=11, verbose_name='موبایل گیرنده')),
                ('ship_to_city', models.CharField(max_length=100, verbose_name='شهر')),
                ('ship_to_address', models.TextField(verbose_name='نشانی')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('receipt_uploaded', 'فیش آپلود شد - در انتظار تایید'), ('confirmed', 'پرداخت تایید شد'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل شد'), ('canceled', 'لغو شد (عدم پرداخت)'), ('credit', 'خرید اعتباری')], db_index=True, default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('credit', 'اعتباری')], default='card_to_card', max_length=20, verbose_name='روش پرداخت')),
                ('subtotal', models.PositiveBigIntegerField(default=0, verbose_name='جمع کل')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف')),
                ('total', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ نهایی')),
                ('coupon_code', models.CharField(blank=True, max_length=40, verbose_name='کد تخفیف')),
                ('receipt_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت آپلود فیش')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید پرداخت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.orders.models.receipt_upload_path, verbose_name='تصویر فیش')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پیگیری')),
                ('paid_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ واریزی')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_receipts', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فیش واریزی',
                'verbose_name_plural': 'فیش\u200cهای واریزی',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
