# Generated by Django 5.2.16 on 2026-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_ship_lat_order_ship_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('receipt_uploaded', 'فیش آپلود شد - در انتظار تایید'), ('confirmed', 'پرداخت تایید شد'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل شد'), ('canceled', 'لغو شد (عدم پرداخت)'), ('credit', 'خرید اعتباری')], db_index=True, default='pending_payment', max_length=20, verbose_name='وضعیت'),
        ),
    ]
