# Generated by Django 5.2.16 on 2026-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین یادآوری به تامین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_reminder_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد یادآوری تامین'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('online', 'پرداخت آنلاین'), ('credit', 'اعتباری')], default='card_to_card', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
