# Generated by Django 5.2.16 on 2026-07-11 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pg_trgm_and_authenticity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_qty', models.PositiveIntegerField(verbose_name='از تعداد')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت واحد (تومان)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'پله قیمت عمده',
                'verbose_name_plural': 'قیمت پلکانی',
                'ordering': ('min_qty',),
                'unique_together': {('product', 'min_qty')},
            },
        ),
    ]
