# Generated by Django 5.2.16 on 2026-07-20 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pricetier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RarePartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_name', models.CharField(max_length=200, verbose_name='نام قطعه')),
                ('car_name', models.CharField(max_length=100, verbose_name='نام خودرو')),
                ('car_model', models.CharField(max_length=100, verbose_name='مدل خودرو')),
                ('brand', models.CharField(max_length=100, verbose_name='برند موردنیاز')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rare-parts/', verbose_name='تصویر قطعه (اختیاری)')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('searching', 'در حال پیگیری'), ('found', 'پیدا شد'), ('unavailable', 'موجود نیست')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.CharField(blank=True, max_length=300, verbose_name='پاسخ تامین\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rare_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست قطعه نایاب',
                'verbose_name_plural': 'درخواست\u200cهای قطعه نایاب',
                'ordering': ('-created_at',),
            },
        ),
    ]
