# Generated by Django 5.2.17 on 2026-09-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_brand_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, db_index=True, help_text='محصولاتی با همین مقدار، به\u200cعنوان «گزینه\u200cهای دیگر» این کالا نمایش داده می\u200cشوند.', max_length=220, verbose_name='گروه گزینه\u200cهای دیگر'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text='مثلا: دیاق فلزی — روی دکمه انتخاب گزینه\u200cها نمایش داده می\u200cشود.', max_length=60, verbose_name='برچسب این گزینه'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='خالی = برای همه رنگ\u200cها نمایش داده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.color', verbose_name='رنگ مرتبط'),
        ),
    ]
