# Generated by Django 5.2.16 on 2026-07-10 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.PositiveBigIntegerField(default=0, verbose_name='سقف اعتبار (تومان)')),
                ('settlement_days', models.PositiveSmallIntegerField(default=7, verbose_name='مهلت تسویه (روز)')),
                ('reminder_days', models.PositiveSmallIntegerField(blank=True, help_text='خالی = استفاده از پیش\u200cفرض تامین\u200cکننده', null=True, verbose_name='روزهای یادآوری قبل از سررسید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to=settings.AUTH_USER_MODEL, verbose_name='فروشگاه')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_credit_accounts', to=settings.AUTH_USER_MODEL, verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'حساب اعتباری',
                'verbose_name_plural': 'حساب\u200cهای اعتباری',
                'unique_together': {('supplier', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='CreditInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(db_index=True, verbose_name='سررسید')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تسویه شده')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال یادآوری')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='suppliers.creditaccount', verbose_name='حساب اعتباری')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_invoice', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور اعتباری',
                'verbose_name_plural': 'فاکتورهای اعتباری',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='SupplierSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_reminder_days', models.PositiveSmallIntegerField(default=2, verbose_name='پیش\u200cفرض روزهای یادآوری قبل از سررسید')),
                ('sms_reminders_enabled', models.BooleanField(default=True, verbose_name='ارسال پیامک یادآوری')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('card_holder', models.CharField(blank=True, max_length=100, verbose_name='به نام')),
                ('reminder_template', models.TextField(blank=True, help_text='متغیرها: {shop} {amount} {due} {days}', verbose_name='قالب پیامک یادآوری')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_settings', to=settings.AUTH_USER_MODEL, verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'تنظیمات تامین\u200cکننده',
                'verbose_name_plural': 'تنظیمات تامین\u200cکننده',
            },
        ),
    ]
