# Generated by Django 5.2.16 on 2026-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersettings',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='iban',
            field=models.CharField(blank=True, help_text='بدون IR یا با IR', max_length=26, verbose_name='شماره شبا'),
        ),
    ]
