# Generated by Django 5.2.16 on 2026-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_suppliersettings_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersettings',
            name='online_payment_enabled',
            field=models.BooleanField(default=False, verbose_name='پرداخت آنلاین (درگاه بانکی)'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='order_notify_enabled',
            field=models.BooleanField(default=True, verbose_name='پیامک سفارش جدید به تامین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='order_notify_name',
            field=models.CharField(blank=True, help_text='مثلا: محمدی — در پیامک «جناب آقای …» می\u200cآید.', max_length=100, verbose_name='نام تامین\u200cکننده در پیامک'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='order_notify_phone',
            field=models.CharField(blank=True, help_text='خالی بماند، به موبایل حساب تامین\u200cکننده ارسال می\u200cشود.', max_length=11, verbose_name='موبایل دریافت پیامک سفارش'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='order_notify_template',
            field=models.TextField(blank=True, help_text='متغیرها: {name} {items} {number}', verbose_name='قالب پیامک سفارش جدید'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='order_reminder_hours',
            field=models.PositiveSmallIntegerField(default=3, help_text='هر چند ساعت تا زمانی که سفارش تایید نشده، دوباره پیامک شود.', verbose_name='فاصله یادآوری تا تایید (ساعت)'),
        ),
        migrations.AddField(
            model_name='suppliersettings',
            name='receipt_payment_enabled',
            field=models.BooleanField(default=True, verbose_name='پرداخت با فیش بانکی (کارت به کارت)'),
        ),
    ]
