# Generated by Django 5.2.17 on 2026-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0004_alter_suppliersettings_receipt_payment_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliersettings",
            name="order_notify_template",
            field=models.TextField(
                blank=True,
                help_text="متغیرها: {name} {items} {number} {site}",
                verbose_name="قالب پیامک سفارش جدید",
            ),
        ),
        migrations.AlterField(
            model_name="suppliersettings",
            name="reminder_template",
            field=models.TextField(
                blank=True,
                help_text="متغیرها: {shop} {amount} {due} {days} {site}",
                verbose_name="قالب پیامک یادآوری",
            ),
        ),
    ]
