# Generated by Django 5.2.16 on 2026-07-10 08:05

import apps.accounts.managers
import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(choices=[('admin', 'مدیر سایت'), ('supplier', 'تامین\u200cکننده اصلی'), ('shopkeeper', 'فروشگاه لوازم یدکی'), ('customer', 'کاربر عادی')], db_index=True, default='customer', max_length=20, verbose_name='نقش')),
                ('is_approved', models.BooleanField(default=False, help_text='فروشگاه\u200cها تا زمان تایید امکان خرید عمده ندارند.', verbose_name='تایید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی به پنل مدیریت')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='موبایل تایید شده')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='مثلا: انبار مرکزی', max_length=100, verbose_name='عنوان')),
                ('receiver_name', models.CharField(max_length=150, verbose_name='نام گیرنده')),
                ('receiver_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='موبایل گیرنده')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('line', models.TextField(verbose_name='نشانی کامل')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ('-is_default', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ShopkeeperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('owner_national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی مالک')),
                ('business_license_no', models.CharField(blank=True, max_length=50, verbose_name='شماره جواز کسب')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='آدرس فروشگاه')),
                ('landline', models.CharField(blank=True, max_length=20, verbose_name='تلفن ثابت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت احراز هویت')),
                ('review_note', models.TextField(blank=True, verbose_name='یادداشت بررسی')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shops', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل فروشگاه',
                'verbose_name_plural': 'پروفایل فروشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('national_card', 'کارت ملی'), ('business_license', 'جواز کسب'), ('shop_photo', 'تصویر فروشگاه'), ('other', 'سایر')], max_length=30, verbose_name='نوع مدرک')),
                ('file', models.FileField(upload_to=apps.accounts.models.kyc_upload_path, verbose_name='فایل')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.shopkeeperprofile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'مدرک احراز هویت',
                'verbose_name_plural': 'مدارک احراز هویت',
            },
        ),
    ]
