# Generated by Django 5.2.16 on 2026-07-10 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('purpose', models.CharField(choices=[('password_reset', 'بازیابی رمز عبور')], default='password_reset', max_length=30, verbose_name='کاربرد')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف',
                'verbose_name_plural': 'کدهای یکبارمصرف',
            },
        ),
    ]
