# Generated by Django 5.2.16 on 2026-07-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_lat_address_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سایت'), ('supplier', 'تامین\u200cکننده اصلی'), ('shopkeeper', 'فروشگاه لوازم یدکی'), ('customer', 'کاربر عادی'), ('partner', 'شریک درآمدی')], db_index=True, default='customer', max_length=20, verbose_name='نقش'),
        ),
    ]
