# Generated by Django 5.2.17 on 2026-09-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "مدیر سایت"),
                    ("supplier", "تامین\u200cکننده"),
                    ("shopkeeper", "فروشگاه لوازم یدکی"),
                    ("customer", "کاربر عادی"),
                    ("partner", "شریک درآمدی"),
                ],
                db_index=True,
                default="customer",
                max_length=20,
                verbose_name="نقش",
            ),
        ),
    ]
